/**
 * Comprehensive Bilingual Dictionary (Vietnamese 🇻🇳 & Traditional Chinese 繁體中文 🇹🇼 - Tiếng Đài Loan)
 */

export const translations = {
  vi: {
    // Navbar & App Titles
    appTitle: 'Hệ Thống Chấm Công 5 Chi Nhánh',
    attendanceTab: 'Bảng Chấm Công',
    shiftEntryTab: '✍️ Nhập Ca Làm Việc',
    weeklyRosterTab: '📅 Bảng Sắp Ca Tuần',
    employeesTab: 'Quản Lý Nhân Viên',
    usersTab: 'Tài Khoản Quản Lý',
    exportExcel: 'Xuất Excel',
    salaryAdvanceBtn: '💸 Ứng Lương',
    logout: 'Thoát',
    login: 'Đăng Nhập',
    username: 'Tên Đăng Nhập',
    password: 'Mật Khẩu',
    month: 'Tháng',
    year: 'Năm',
    week: 'Tuần',
    branch: 'Chi Nhánh',
    allBranches: 'Tất Cả Chi Nhánh',
    adminMode: '👑 Admin Mode',
    searchPlaceholder: 'Tìm kiếm nhân viên theo tên hoặc STT...',
    totalEmployees: 'Tổng Nhân Viên',
    workingToday: 'Đi Làm Hôm Nay',
    offToday: 'Nghỉ (OFF) Hôm Nay',
    totalHoursMonth: 'Tổng Giờ Làm Tháng',
    stt: 'STT',
    employeeName: 'NHÂN VIÊN',
    shiftType: 'CA',
    shiftStart: 'Lên Ca',
    shiftEnd: 'Xuống Ca',
    editShift: 'Sửa Ca',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Sửa',
    add: 'Thêm',

    // Attendance Matrix Header & Locks
    attendanceGridTitle: 'Bảng Chấm Công',
    lockedFromDay: 'Từ ngày {day} trở đi bị khóa',
    selectedBranch: 'Chi nhánh đang chọn',

    // Shift Entry Page
    shiftEntryTitle: 'Trang Nhập Ca Làm Việc Cho Nhân Viên',
    shiftEntrySub: 'Hỗ trợ chọn ca gãy cho cả 👔 Full-Time (Tự động tính gộp tổng giờ) và ⏱️ Part-Time (Tách 2 ca độc lập).',
    step1SelectEmp: '1. Chọn Nhân Viên:',
    step2SelectDate: '2. Chọn Ngày Chấm Công',
    step3QuickPreset: '3. Nút Chọn Ca Nhanh:',
    presetFull: 'Ca Full (8h – 22h)',
    presetMorning: 'Ca Sáng (8h – 17h)',
    presetEvening: 'Ca Tối (13h – 22h)',
    presetShortMorning: 'Sáng Ngắn (8h – 13h)',
    presetShortEvening: 'Tối Ngắn (17h – 22h)',
    presetSplit1: 'Ca Gãy (8h–12h & 17h–22h)',
    presetSplit2: 'Ca Gãy (8h–13h & 17h–22h)',
    partTimeBadge: 'Nhân viên Part-Time (Ca Gãy)',
    fullTimeBadge: 'Nhân viên Full-Time',
    saveShiftBtn: 'Lưu Ca Làm Việc',

    // Weekly Roster Page
    rosterPageTitle: 'Trang Sắp Ca Theo Tuần (Weekly Shift Roster)',
    rosterPageSub: 'Sắp xếp lịch phân ca tuần cho các chi nhánh (Ca 8h-13h, 13h-17h, 17h-22h). Nhân viên sẽ xem được bảng ca này khi đăng nhập.',
    branchRosterTitle: 'Bảng Sắp Ca Chi Nhánh',
    swipeHint: '👉 Vuốt sang phải để xem đủ Thứ 2 ➔ Chủ Nhật',
    clickToEdit: '💡 Nhấp vào ô để xếp/sửa ca',
    clearWeekBtn: 'Xóa Lịch Ca Tuần Này',
    clearDayBtn: 'Xóa ngày',
    clearCellBtn: 'Xóa trắng ô này',
    saveRosterBtn: 'Lưu Phân Ca',
    forEmployeesOnly: '(Dành Riêng Cho Nhân Viên)',
    selectWeek: 'Chọn Tuần:',

    // Days of Week
    Mon: 'Thứ 2',
    Tue: 'Thứ 3',
    Wed: 'Thứ 4',
    Thu: 'Thứ 5',
    Fri: 'Thứ 6',
    Sat: 'Thứ 7',
    Sun: 'Chủ Nhật',

    // Shifts & Types
    shiftMorning: '8h - 13h',
    shiftAfternoon: '13h - 17h',
    shiftEvening: '17h - 22h',
    fullTime: 'Full-Time',
    partTime: 'Part-Time',

    // Employees Management Page
    empListTitle: '5 Chi Nhánh Danh Sách Nhân Viên',
    empListSub: 'Quản lý danh sách nhân viên 5 chi nhánh (Chính thức & Bán thời gian)',
    addNewEmp: 'Thêm Nhân Viên',
    empTypeLabel: 'Loại Hình Làm Việc:',
    nameInputPlaceholder: 'Nhập tên nhân viên...',
    actions: 'Thao Tác',

    // Users Management Page
    userListTitle: 'Đổi Quyền Hạn & Quản Lý Tài Khoản',
    userListSub: 'Cấp tài khoản đăng nhập (Admin, Quản Lý Chi Nhánh, Nhân Viên)',
    addNewUser: 'Thêm Tài Khoản Mới',
    accountName: 'Tài Khoản:',
    fullName: 'Họ và Tên:',
    roleLabel: 'Quyền Hạn:',
    userPlaceholder: 'VD: ql_bienhoa',
    passwordPlaceholder: 'Mật khẩu...',
    fullNamePlaceholder: 'VD: Nguyễn Văn A',
    branchManagerRole: 'Quản Lý Chi Nhánh (Manager)',
    employeeRole: 'Nhân Viên (Employee)',
    adminRole: 'Quản Trị Viên (Admin)',
    managerBadge: 'Quản Lý',
    employeeBadge: 'Nhân Viên',
    adminBadge: 'Admin',

    // Salary Advance Modal
    salaryAdvanceTitle: '💸 Quản Lý Ứng Lương Nhân Viên',
    totalAdvanced: 'Tổng đã ứng:',
    tabAddNewAdvance: 'Tạo Phiếu Ứng Mới',
    tabAdvanceHistory: 'Lịch Sử Ứng Lương',
    selectEmpAdvance: '👤 Chọn Nhân Viên Ứng Tiền:',
    filterBranch: '🏢 Lọc Chi Nhánh:',
    advanceDate: '📅 Ngày Ứng:',
    advanceAmount: '💵 Số Tiền Ứng (VNĐ):',
    quickSelect: 'Chọn nhanh:',
    noteReason: '📝 Ghi Chú / Lý Do:',
    notePlaceholder: 'Ví dụ: Ứng giữa tháng, Ứng mua đồ...',
    saveAdvanceBtn: '💾 Lưu Phiếu Ứng Lương',
    noAdvancesMonth: 'Chưa có lượt ứng lương nào trong tháng',
    noteColumn: 'Ghi Chú',
    actionColumn: 'Thao Tác',

    // Login Page
    loginTitle: 'Đăng Nhập Hệ Thống Chấm Công',
    loginSub: 'Nhập tài khoản để quản lý chấm công hoặc xem ca làm việc cá nhân',
    loginBtn: 'Đăng Nhập Hệ Thống',
    rememberMe: 'Ghi nhớ đăng nhập',

    // Employee Portal
    employeePortalTitle: 'Cổng Thông Tin Nhận Ca Cá Nhân',
    employeePortalSub: 'Dành riêng cho Nhân viên',
    myBranchRosterTab: '📅 Bảng Sắp Ca Chi Nhánh',
    myListViewTab: '📱 Dạng Danh Sách',
    myMatrixViewTab: '📊 Dạng Matrix',
    workingDaysCount: 'Số Ca Đi Làm',
    offDaysCount: 'Số Ngày Nghỉ (OFF)',
    totalHoursCount: 'Tổng Giờ Làm',
    salaryAdvancedCount: 'Số Tiền Đã Ứng',
    editAccountBtn: 'Sửa Tài Khoản',
    shiftUnit: 'ca',
    dayUnit: 'ngày',
    hourUnit: 'tiếng',
    today: 'Hôm nay',
    notYet: 'Chưa tới',
    dayOff: 'Nghỉ (OFF)',
    scheduled: 'Đã Xếp Ca',
    splitShift: 'Ca Gãy',
    notScheduled: 'Chưa phân ca',

    // Language Toggle
    langName: '🇻🇳 Tiếng Việt',
    switchLang: '🇹🇼 繁體中文'
  },

  zh: {
    // Navbar & App Titles
    appTitle: '5門市考勤打卡管理系統',
    attendanceTab: '考勤打卡表',
    shiftEntryTab: '✍️ 班表輸入',
    weeklyRosterTab: '📅 週排班表',
    employeesTab: '員工管理',
    usersTab: '管理員帳號',
    exportExcel: '匯出 Excel',
    salaryAdvanceBtn: '💸 預支薪資',
    logout: '登出',
    login: '登入',
    username: '帳號',
    password: '密碼',
    month: '月',
    year: '年',
    week: '週',
    branch: '門市 / 分店',
    allBranches: '所有門市',
    adminMode: '最高管理員模式',
    searchPlaceholder: '搜尋員工姓名或編號...',
    totalEmployees: '總員工人數',
    workingToday: '今日出勤',
    offToday: '今日休假 (OFF)',
    totalHoursMonth: '本月總工時',
    stt: '序號',
    employeeName: '員工姓名',
    shiftType: '班次',
    shiftStart: '上班',
    shiftEnd: '下班',
    editShift: '修改班次',
    save: '儲存',
    cancel: '取消',
    delete: '刪除',
    edit: '編輯',
    add: '新增',

    // Attendance Matrix Header & Locks
    attendanceGridTitle: '考勤打卡表',
    lockedFromDay: '從 {day} 號起鎖定',
    selectedBranch: '當前選擇門市',

    // Shift Entry Page
    shiftEntryTitle: '員工排班 / 班表輸入頁面',
    shiftEntrySub: '支援正職 👔 Full-Time（自動合併總工時）與兼職 ⏱️ Part-Time（拆 2 班）快捷排班。',
    step1SelectEmp: '1. 選擇員工:',
    step2SelectDate: '2. 選擇打卡日期',
    step3QuickPreset: '3. 快速選擇班別 (Presets):',
    presetFull: '全天班 (8h – 22h)',
    presetMorning: '早班 (8h – 17h)',
    presetEvening: '晚班 (13h – 22h)',
    presetShortMorning: '短早班 (8h – 13h)',
    presetShortEvening: '短晚班 (17h – 22h)',
    presetSplit1: '拆班 (8h–12h & 17h–22h)',
    presetSplit2: '拆班 (8h–13h & 17h–22h)',
    partTimeBadge: '兼職員工 (拆班)',
    fullTimeBadge: '正職員工',
    saveShiftBtn: '儲存工作班次',

    // Weekly Roster Page
    rosterPageTitle: '門市週排班表管理 (Weekly Shift Roster)',
    rosterPageSub: '安排各門市每週班表（早班 8h-13h、中班 13h-17h、晚班 17h-22h）。員工登入後可即時查看本門市班表。',
    branchRosterTitle: '門市週排班表',
    swipeHint: '👉 向右滑動查看完整週一至週日',
    clickToEdit: '💡 點擊儲存格進行排班/編輯',
    clearWeekBtn: '清除本週排班',
    clearDayBtn: '清除此日',
    clearCellBtn: '清除此時段',
    saveRosterBtn: '儲存排班',
    forEmployeesOnly: '(員工專用看班表)',
    selectWeek: '選擇週次:',

    // Days of Week
    Mon: '星期一',
    Tue: '星期二',
    Wed: '星期三',
    Thu: '星期四',
    Fri: '星期五',
    Sat: '星期六',
    Sun: '星期日',

    // Shifts & Types
    shiftMorning: '8h - 13h (早班)',
    shiftAfternoon: '13h - 17h (中班)',
    shiftEvening: '17h - 22h (晚班)',
    fullTime: '正職 (Full-Time)',
    partTime: '兼職 (Part-Time)',

    // Employees Management Page
    empListTitle: '5 家門市員工名單',
    empListSub: '管理 5 家門市員工名單 (正職 & 兼職)',
    addNewEmp: '新增員工',
    empTypeLabel: '工作類型:',
    nameInputPlaceholder: '請輸入員工姓名...',
    actions: '編輯 / 刪除',

    // Users Management Page
    userListTitle: '店長與管理員帳號管理',
    userListSub: '設定與發放帳號權限（最高管理員 Admin、門市店長 Manager、員工 Employee）',
    addNewUser: '新增帳號',
    accountName: '帳號:',
    fullName: '姓名:',
    roleLabel: '權限等級:',
    userPlaceholder: '例: ql_bienhoa',
    passwordPlaceholder: '密碼...',
    fullNamePlaceholder: '例: 王小明',
    branchManagerRole: '門市店長 (Manager)',
    employeeRole: '員工 (Employee)',
    adminRole: '最高管理員 (Admin)',
    managerBadge: '店長',
    employeeBadge: '員工',
    adminBadge: '最高管理員',

    // Salary Advance Modal
    salaryAdvanceTitle: '💸 預支薪資管理',
    totalAdvanced: '總預支金額:',
    tabAddNewAdvance: '建立預支單',
    tabAdvanceHistory: '預支歷史紀錄',
    selectEmpAdvance: '👤 選擇預支員工:',
    filterBranch: '🏢 篩選門市:',
    advanceDate: '📅 預支日期:',
    advanceAmount: '💵 預支金額 (VNĐ):',
    quickSelect: '快速選擇:',
    noteReason: '📝 備註 / 原因:',
    notePlaceholder: '例: 月中預支, 購買物品...',
    saveAdvanceBtn: '💾 儲存預支單',
    noAdvancesMonth: '本月尚無預支紀錄',
    noteColumn: '備註',
    actionColumn: '操作',

    // Login Page
    loginTitle: '考勤打卡管理系統登入',
    loginSub: '請輸入帳號密碼以管理考勤或查看個人班表',
    loginBtn: '登入系統',
    rememberMe: '記住登入狀態',

    // Employee Portal
    employeePortalTitle: '員工個人排班打卡中心',
    employeePortalSub: '員工專用頁面',
    myBranchRosterTab: '📅 門市週排班表',
    myListViewTab: '📱 列表模式',
    myMatrixViewTab: '📊 網格模式',
    workingDaysCount: '出勤班次',
    offDaysCount: '休假天數 (OFF)',
    totalHoursCount: '總工時',
    salaryAdvancedCount: '預支薪資',
    editAccountBtn: '修改帳號',
    shiftUnit: '班',
    dayUnit: '天',
    hourUnit: '小時',
    today: '今天',
    notYet: '未到期',
    dayOff: '休假 (OFF)',
    scheduled: '已排班',
    splitShift: '兩段班',
    notScheduled: '未排班',

    // Language Toggle
    langName: '🇹🇼 繁體中文',
    switchLang: '🇻🇳 Tiếng Việt'
  }
};
